### PR TITLE
"learn more" links from each step of "add a feed" to documentation sections

### LINKED ISSUE #158: "learn more" links from each step of "add a feed" to documentation sections

### PR DESCRIPTION
**Pull request by drewda**
closes #158

### CODE REVIEW

**Comment by rmglennon** [comment]
Let's chat about where these appear on the page. Looks like this goes in the paragraph at the top?

The link text is clear, but is it too long? 

@drewda @souperneon

**Comment by souperneon** [comment]
can someone send me a screenshot for this?

**Comment by drewda** [comment]
feed_registry_ _transitland

feed_registry_ _transitland
feed_registry_ _transitland
feed_registry_ _transitland
feed_registry_ _transitland

**Comment by souperneon** [comment]
I have the same comment i always do :) too much text! We need to just overall cut text down but to be specific for these links (because they are links) we can shorten them to be:
- learn more about GTFS feeds (because its more that just finding one)
- Learn more about transit operators
- learn more about licenses
learn more about how to submit can be removed imo. What does this one have?
- learn more about feed submissions

How is that?

**Comment by rmglennon** [comment]
I shortened the link text to @souperneon's suggestions and removed the links from the Tell us a little bit and thank you pages. The UI text here should be good enough to explain what's going on here and the help doesn't add much. Let's keep "Learn more" links short and only where really needed. This makes us rely on good UX and pop-ups instead of kicking people off the page to go into the help.

I also removed a line about fields being optional/required on the operators page. This came up in some other issue about this page. We have UI hints, so no need to repeat it.

**Pull request merged**
